export const ordersData = [
  {
    id: "1",
    date: "2023-01-01",
    status: "Paid",
    customer: "Alice Murinho",
    productName: "Product A",
    revenue: 50.0,
  },
  {
    id: "2",
    date: "2023-01-02",
    status: "Canceled",
    customer: "Alice Murinho",
    productName: "Product B",
    revenue: 75.5,
  },
  {
    id: "3",
    date: "2023-01-03",
    status: "Paid",
    customer: "Alice Murinho",
    productName: "Product C",
    revenue: 30.25,
  },
  {
    id: "1",
    date: "2023-01-01",
    status: "Paid",
    customer: "Alice Murinho",
    productName: "Product A",
    revenue: 50.0,
  },
  {
    id: "2",
    date: "2023-01-02",
    status: "Canceled",
    customer: "Alice Murinho",
    productName: "Product B",
    revenue: 75.5,
  },
  {
    id: "3",
    date: "2023-01-03",
    status: "Paid",
    customer: "Alice Murinho",
    productName: "Product C",
    revenue: 30.25,
  },
  {
    id: "1",
    date: "2023-01-01",
    status: "Paid",
    customer: "Alice Murinho",
    productName: "Product A",
    revenue: 50.0,
  },
  {
    id: "2",
    date: "2023-01-02",
    status: "Canceled",
    customer: "Alice Murinho",
    productName: "Product B",
    revenue: 75.5,
  },
  {
    id: "3",
    date: "2023-01-03",
    status: "Paid",
    customer: "Alice Murinho",
    productName: "Product C",
    revenue: 30.25,
  },
  {
    id: "1",
    date: "2023-01-01",
    status: "Paid",
    customer: "Alice Murinho",
    productName: "Product A",
    revenue: 50.0,
  },
  {
    id: "2",
    date: "2023-01-02",
    status: "Canceled",
    customer: "Alice Murinho",
    productName: "Product B",
    revenue: 75.5,
  },
  {
    id: "3",
    date: "2023-01-03",
    status: "Paid",
    customer: "Alice Murinho",
    productName: "Product C",
    revenue: 30.25,
  },
];
