export const ordersData = [
  {
    id: "1",
    date: "2023-01-01",
    status: "Paid",
    customer: "Alice Murinho",
    productName: "Product A",
    revenue: 50.0,
  },
  {
    id: "2",
    date: "2023-01-02",
    status: "Canceled",
    customer: "Alice Murinho",
    productName: "Product B",
    revenue: 75.5,
  },
  {
    id: "3",
    date: "2023-01-03",
    status: "Paid",
    customer: "Alice Murinho",
    productName: "Product C",
    revenue: 30.25,
  },
  {
    id: "4",
    date: "2023-01-01",
    status: "Paid",
    customer: "Alice Murinho",
    productName: "Product A",
    revenue: 50.0,
  },
  {
    id: "5",
    date: "2023-01-02",
    status: "Canceled",
    customer: "Alice Murinho",
    productName: "Product B",
    revenue: 75.5,
  },
  {
    id: "6",
    date: "2023-01-03",
    status: "Paid",
    customer: "Alice Murinho",
    productName: "Product C",
    revenue: 30.25,
  },
  {
    id: "7",
    date: "2023-01-01",
    status: "Paid",
    customer: "Alice Murinho",
    productName: "Product A",
    revenue: 50.0,
  },
  {
    id: "8",
    date: "2023-01-02",
    status: "Canceled",
    customer: "Alice Murinho",
    productName: "Product B",
    revenue: 75.5,
  },
  {
    id: "9",
    date: "2023-01-03",
    status: "Paid",
    customer: "Alice Murinho",
    productName: "Product C",
    revenue: 30.25,
  },
  {
    id: "10",
    date: "2023-01-01",
    status: "Paid",
    customer: "Alice Murinho",
    productName: "Product A",
    revenue: 50.0,
  },
  {
    id: "11",
    date: "2023-01-02",
    status: "Canceled",
    customer: "Alice Murinho",
    productName: "Product B",
    revenue: 75.5,
  },
  {
    id: "12",
    date: "2023-01-03",
    status: "Paid",
    customer: "Alice Murinho",
    productName: "Product C",
    revenue: 30.25,
  },
];


export const orderProductsData = [
  {
    id: "1",
    image: "/assets/img/profile/image1.png",
    name: "Wireless Headphone (Black)",
    units: 1,
    revenue: 50.0,
  },
  {
    id: "1",
    image: "/assets/img/profile/image1.png",
    name: "Wireless Headphone (Black)",
    units: 1,
    revenue: 50.0,
  },
  {
    id: "1",
    image: "/assets/img/profile/image1.png",
    name: "Wireless Headphone (Black)",
    units: 1,
    revenue: 50.0,
  }
];
